apiVersion: v1
kind: Service
metadata:
  name: {{ template "nft-market.name" . }}-rabbit
  labels:
    app: {{ template "nft-market.name" . }}-rabbit
    chart: {{ template "nft-market.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - name: rabbit
      port: 5672
      targetPort: 5672
      protocol: TCP
  selector:
    app: {{ template "nft-market.name" . }}-rabbit
    release: {{ .Release.Name }}
