apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ template "nft-market.name" . }}
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
